services:
  cassandra-db:
    image: "cassandra:4.1"
    ports:
      - "9042:9042"
      - "7000:7000"
    networks:
      - db

  db-migrator:
    build: db-migrator
    container_name: db-migrator
    command: liquibase status
    volumes:
      - liquibase-data:/liquibase/changelog
    depends_on:
      - cassandra-db
    networks:
      - db

volumes:
  liquibase-data:
    external: true

networks:
  db:
    name: db
    driver: bridge
